//
//  MathProblemTests.swift
//  MentalMathAppTests
//
//  Unit tests for MathProblem model.
//

import XCTest
@testable import MentalMathApp

final class MathProblemTests: XCTestCase {

    // MARK: - Correct Answer Tests

    func testCorrectAnswerAddition() {
        let problem = MathProblem(operandA: 15, operandB: 27, operation: .addition)
        XCTAssertEqual(problem.correctAnswer, 42)
    }

    func testCorrectAnswerSubtraction() {
        let problem = MathProblem(operandA: 50, operandB: 23, operation: .subtraction)
        XCTAssertEqual(problem.correctAnswer, 27)
    }

    func testCorrectAnswerMultiplication() {
        let problem = MathProblem(operandA: 12, operandB: 11, operation: .multiplication)
        XCTAssertEqual(problem.correctAnswer, 132)
    }

    func testCorrectAnswerDivision() {
        let problem = MathProblem(operandA: 100, operandB: 4, operation: .division)
        XCTAssertEqual(problem.correctAnswer, 25)
    }

    // MARK: - Display Text Tests

    func testDisplayTextAddition() {
        let problem = MathProblem(operandA: 3, operandB: 5, operation: .addition)
        XCTAssertEqual(problem.displayText, "3 + 5")
    }

    func testDisplayTextMultiplication() {
        let problem = MathProblem(operandA: 7, operandB: 8, operation: .multiplication)
        XCTAssertEqual(problem.displayText, "7 × 8")
    }

    // MARK: - Identity Tests

    func testAutoGeneratedIdIsUnique() {
        let a = MathProblem(operandA: 1, operandB: 2, operation: .addition)
        let b = MathProblem(operandA: 1, operandB: 2, operation: .addition)
        XCTAssertNotEqual(a.id, b.id)
    }

    func testExplicitIdIsPreserved() {
        let fixedId = UUID()
        let problem = MathProblem(id: fixedId, operandA: 1, operandB: 2, operation: .addition)
        XCTAssertEqual(problem.id, fixedId)
    }

    // MARK: - Equatable Tests

    func testEqualProblemsWithSameId() {
        let fixedId = UUID()
        let a = MathProblem(id: fixedId, operandA: 5, operandB: 3, operation: .addition)
        let b = MathProblem(id: fixedId, operandA: 5, operandB: 3, operation: .addition)
        XCTAssertEqual(a, b)
    }

    func testUnequalProblemsDifferentOperands() {
        let fixedId = UUID()
        let a = MathProblem(id: fixedId, operandA: 5, operandB: 3, operation: .addition)
        let b = MathProblem(id: fixedId, operandA: 5, operandB: 4, operation: .addition)
        XCTAssertNotEqual(a, b)
    }
}
